### PR TITLE
Updated language in the README

### PR DESCRIPTION
**Pull request by AugP**
Converted the README to describe this particular fork of the project.

### CODE REVIEW

**Comment by LukaszMendakiewicz** [comment]
This may be problematic later when integrating back to upstream. I am not sure if we **really** want to do this, and if so if Christian et al. has preference how we approach this.

**Comment by AugP** [comment]
We should differentiate between our fork and the original adapter since they're not functionally similar. For example, the original wiki described acquiring the adapter as a nuget package, something which this fork does not currently support. I don't think we can keep the content identical here, isn't there some way to differentiate them while still keeping future merges between the forks manageable?

**Comment by LukaszMendakiewicz** [comment]
Unfortunately what GitHub presents on the repo "home page" is the contents of README.md, which is versioned in the source control (and thus integrates between forks). Wiki is per repo though. Maybe we can draft up a shared README.md that would be applicable to us and upstream, and redirect readers to more information in respective Wikis, which would contain the differences?

**Comment by csoltenborn** [comment]
I see two priorities at first thought: Having documentation as part of the `READ_ME.md` (since it's the natural landing page for users) and avoiding duplications.

Having said that, every time I see *forked from*, I wonder what the differences are between the original and the fork. Plus, if we follow the "develop and stabilize on GTA and then merge to TAfGT" approach, our differences should stay small, and our collaboration will (hopefully) be rather tight. All together, it might make sense to indeed have a shared version of the page, for instance with

* a neutral headline such as *Google Test in Visual Studio*,
* a section briefly introducing GTA and TAfGT (and speaking of *the adapter* for the rest of the documentation)
* a documentation section (with tags *GTA/TAfGT only* where applicable), 
* a section *Features under development* (or such) containing stuff which has not yet made it into TAfGT, 
* a *Trouble shooting* section,
* a dedicated *NuGet* section, and
* a *Credits* section.

Just to mention another option: We could also come up with a smaller, common landing page and then link to *GTA* and *TAfGT* sections (which could e.g. live in according subfolders of a `docs` folder). Drawback would be that users would have to navigate a bit (for now, I feel that having all information on one page is very appropriate).

Lukasz' suggestion is worth a thought, too - however, the one thing I like about having the docs as part of the repository is that it's in a consistent state for a particular (tagged) version. I have in fact thought about moving the development docs back from the Wiki to the repository because of this.

**Comment by AugP** [comment]
Bringing this back up - I agree with your assessment @csoltenborn about having a common landing page between the two repos. I think it would be a better approach than having links to two separate pages since it requires an extra action from the user and if the user is just quickly skimming the page, it may appear that there isn't a lot of information immediately available (I know I've ignored important links many times in the past online because they didn't "jump out" to me, and I end up navigating elsewhere and missing them entirely). I'm linking Nick (who is also joining this project) as well to take a look and provide his comments. Once we agree on the approach we can update this PR.

**Comment by nickuhlenhuth** [comment]
Having a common landing page for the two repos is okay, and I agree with most of the bullets @csoltenborn listed. The one bullet I'm not convinced about is 'a documentation section (with tags GTA/TAfGT only where applicable),'.
Using tags is one approach. Another approach would be to have a section entirely documenting TAfGT. For items that differ from GTA, we can use footnote references rather than cluttering with the TAfGT/GTA alternative approaches whenever there is a difference.

**Comment by csoltenborn** [comment]
I must admit that I don't like the footnotes idea too much, since footnotes are very abstract (`[1]`) and force the user to click them.

As far as I can see, the only difference so far is going to be the templates (which had not been ported to GTA by Lukasz, but will be ported by me in the coming weeks). Assuming that the differences between the adapters stay tiny, I proposed a "neutral" documentation with, err, that single tag `TAfGT only` or `Not supported by GTA` for the templates stuff, making the differences very clear to the reader. We could additionally structure the documentation part such that the differences are documented at the end, reducing "cluttering" further more... What do you think?

**Comment by AugP** [comment]
I think that's a fair point. I'll ask Nick to work on a draft and update this PR. He is on vacation this week though so hopefully we'll get one out sometime after that.

**Comment by csoltenborn** [comment]
Sounds good! Please note that I am on vacation from Thursday on (for 2.5 weeks) - I will read email occasionally, but probably do not want to write lengthy replies because I don't have a laptop with me...

**Review by LukaszMendakiewicz — DISMISSED** [review]
Please make sure you sync with @csoltenborn that the current version is OK for both sides.

**Review by nickuhlenhuth — APPROVED** [review]

**Pull request merged**
