### PR TITLE
add a message popup when project creation fails due to sdk not found

### PR DESCRIPTION
**Pull request by spebl**

### CODE REVIEW

**Comment by LukaszMendakiewicz** [comment]
Related to #19.

**Review by rashidsarwar — DISMISSED** [review]

**Comment by LukaszMendakiewicz** [comment]
Please consider fallback to Windows 8.1 SDK.

**Review by LukaszMendakiewicz — APPROVED** [review]

**Comment by meegta** [comment]
dev17

**Comment by meegta** [comment]
dev17

**Comment by meegta** [comment]
gh pr checkout 22

**Pull request merged**
