### PR TITLE
#167 - Update GoogleTest.targets.tt - allow nonstandard build configs 

### PR DESCRIPTION
**Pull request by ncook-hxgn**
This is achieved with the assumption that what's not specifically debug, is release, interms of $(Configuration).

I've done about 1 pull request in my life on Github. If I've done this one wrong, please tell me how to do it right, or point me to some docs if you've got them :)

### CODE REVIEW

**Comment by ncook-hxgn** [comment]
I am awaiting approval from my development manager before signing the CLA, but they are rather busy today.. have patience. 👍

**Comment by ncook-hxgn** [comment]
Hello! :)

This is the first time I tried to resolve a merge conflict on github.

I'd tabbed-in some XML so it would align with the output from the template block in a tt.

I've attempted to resolve the conflicts by just deleting my whitespace changes that caused them.

**Review by nejcgalof — APPROVED** [review]

**Review by nejcgalof — APPROVED** [review]

**Comment by nejcgalof** [comment]
When can we expect this fix in new version?

**Comment by ncook-hxgn** [comment]
As soon as somebody approves the review, it will get merged into a dev branch (I hope):
image

**Comment by nejcgalof** [comment]
@ncook-hxgn It's looks like this repo is not active. You can push this change on https://github.com/csoltenborn/GoogleTestAdapter. Maybe here merge this fix faster.

**Comment by ncook-hxgn** [comment]
@nejcgalof Yeah it looks like you might be right - it's ahead of the forked repo a little bit, but also way behind the forked repo (https://github.com/csoltenborn/GoogleTestAdapter).

Last issue that wasn't closed by the person that raised it was over a year ago..
Was I was tricked into signing an agreement by a robot, to make a fix on a dead repo?

@spebl made a commit not so long ago, maybe they can enlighten us?

**Comment by nejcgalof** [comment]
@ncook-hxgn You can contribute to other forks too, meanwhile we waiting here. @spebl can help us and review this PR. Also who create releases? Last release was created 10 Oct 2017.

**Comment by spebl** [comment]
Hi! Sorry about the delays on the review. I can help review and get this through, I'll take a look at it now. I had seen this originally but was busy working on other projects and this got lost. Tagging me here was super helpful to bring it back up.

**Review by spebl — APPROVED** [review]
Tested the fix and it looks good! Thanks for helping fix this. I'll follow up the PR with my own to prepare a new version of the NuGet package including the fix. Once this is in, it will be included in an upcoming release of Visual Studio. If you want the fix sooner, you'll be able to update your test project's NuGet reference to the latest version once that's uploaded which should be shortly.

**Comment by ncook-hxgn** [comment]
Yay! 😺 

Glad to be of help 😄

**Comment by spebl** [comment]
The NuGet packages should now be available for upgrade with the latest version including this fix!

**Comment by nejcgalof** [comment]
@ncook-hxgn What if I have Configuration with name for example: "Test_Debug" which is like "Debug" with different name. Then I got LNK error: `LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value 0 doesn't match value 2`.
In short: release and debug libs are mixing.

**Pull request merged**
